sudo: required
language: python
branches:
  only: master
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy
  # - pypy3
matrix:
  allow_failures:
    - 2.6
    - nightly
    - pypy
    # - pypy3
  fast_finish: true
cache: pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
  # - sudo apt-get install -y python-pycurl
install:
  - pip install -U setuptools
  - pip install pypandoc
  - pip install requests
  - pip install tox-travis
script: tox --skip-missing-interpreters
# after_success:
  # - pip install scrutinizer-ocular
  # - ocular
before_deploy:
  - test $TRAVIS_TEST_RESULT -eq 0
  - test $TRAVIS_EVENT_TYPE != "cron"
deploy:
  - provider: pypi
    user:
      secure: ""
    password:
      secure: ""
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: master
      python: 3.5
      tags: true
  - provider: releases
    api-key: ""
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      branch: master
      python: 3.5
      tags: true
# after_deploy:
  # - pip install travis-bump-version
  # - travis-bump-version --api-token "" --repo $TRAVIS_REPO_SLUG VERSION
